name: Checkers - Quality
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  check:
    runs-on: decathlon
    steps:
      - name: Pre/Post Cleaners
        uses: dktunited/.github/actions/cleaner@main
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Project
        uses: ./.github/actions/install-project
      - name: Make Checks
        run: make checkers
        env:
          ENV: local
