name: SonarCloud - Reports
on: workflow_dispatch
# Uncomment the following lines to include this workflow in the CI on push
#on:
#  push:
#    branches:
#      - "**"
jobs:
  report:
    runs-on: decathlon
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Pre/Post Cleaners
        uses: dktunited/.github/actions/cleaner@main
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Project
        uses: ./.github/actions/install-project
      - name: Make Reports
        run: make reporters
        env:
          ENV: local
      - name: Deploy Reports
        uses: SonarSource/sonarcloud-github-action@master
