name: Sphinx - Documentation
on:
  push:
    branches:
      - main
jobs:
  document:
    runs-on: decathlon
    steps:
      - name: Pre/Post Cleaners
        uses: dktunited/.github/actions/cleaner@main
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Project
        uses: ./.github/actions/install-project
      - name: Make Documentation
        run: make documenters
        env:
          ENV: local
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/
